#!/usr/bin/perl -w
use strict;

my $yyyy = '';
my %entry;

sub dump_entry {
    %entry || return;

    my $D = $entry{'D'};
    if ($D ne $yyyy) {
	print "</ul>\n\n" if $yyyy;
	print "<h2>$D</h2>\n";
	print "<ul>\n";
	$yyyy = $D;
    }

    my $U = $entry{'U'};
    my $V = $entry{'V'};
    if ($V) {
	$V =~ s/\(/:/;
	$V =~ s/\)//;
	$V =~ s/-/&ndash;/;
	print "<li><p><a href=\"$U\">SBT $V</a>, $D.\n";
    }
    else {
	my $T = $entry{'T'};
	print "<li><p>$T.\n";
    }
    my $X = $entry{'X'};
    if ($X) {
	$X =~ s/<p>INNEH.+?.\s+//;
	$X =~ s/<\/p>$//;
	print "<br>$X\n";
    }
    %entry = ();
}

while (<>) {
    /^$/ and dump_entry(), next;
    /^%(.)\s(.+)/ and $entry{$1} = $2, next;
}

dump_entry();

print "</ul></body></html>\n";

__END__

Copyright (c) 2020 Jörgen Grahn. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

 1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above
    copyright notice, this list of conditions and the following
    disclaimer in the documentation and/or other materials provided
    with the distribution.

 3. Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
